l_simp_chinese:
tot_magic_stone: "法术卷轴"
tot_magic_stone_desc: "将魔石碾成粉末，以一定规律铭刻于特殊处理后的纸张上，便铸就了原始魔导器————法术卷轴。如今这一生产方式从法师订制转向工坊制，让魔法卷轴从昂贵的特殊用品变为了工业品。"
tot_magic_steel: "魔力结构体"
tot_magic_steel_desc: "将魔晶石与钢铁再次冶炼后形成的新型材料。导魔性和强度良好，甚至可以调取魔晶石内的天然魔力，使大批量生产弱超能力者与麻瓜都能使用的粗制魔导器成为可能。"
tot_magictools: "专业魔导器"
tot_magictools_desc: "随着魔导器生产工艺的进步，魔导器足以进一步专业化，即便是普通矿工的一把铁镐，也可能是一把魔导器。"
tot_magic_power: "魔力储存技术"
tot_magic_power_desc: "魔力结构体的出现，让大量且计量的存储计算魔力成为可能。无论是从弱能力者、超能力者身上汲取魔力还是从矿石中获取魔力都是不错的选择。"
tot_mass_magic: "固化大型法术"
tot_mass_magic_desc: "将大型法术通过魔导装置固化，持续供能，使土壤改造·传送货物都成为可能。"
tot_tradition_magic: "经典炼金术"
tot_tradition_magic_desc: "炼金术是基于魔法的、迥异于物理和化学的对物质变动手段。虽然传统炼金术师常说练金学是等价交换、但是物质嬗变过程中原子序数改变应释放或是吸收的大量能量却不翼而飞。因此、对炼金术的使用基本只能遵循经验主义和实用主义，理论上并不完备。"

